apiVersion: v1
kind: Namespace
metadata:
  name: website

---

apiVersion: v1
kind: Deployment
metadata:
  name: dev-server-app
  namespace: website
  label:
    kubernetes.io/app-name: nginx-server
    project-stage: dev
spec:
  selector:
    matchLabels:
      server: nginx
  template:
    metadata:
      labels:
        server: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          request:
            memory: "10Mi"
            cpu: "10m"
        livelinessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          exec:
            args:
            - cat "/usr/share/nginx/html/index.html"
        volumeMount:
        
        ports:
        - containerPort: 80
          name: nginx-port

---

apiVerson: v1
kind: Service
metadata:
  name: nginx-dev-svc
  namespace: website
spec:
  type: LoadBalancer
  ports:
  - name: service
    port: 9091
    targetPort: nginx-port
    nodePort: 31000
  selector:
    server: nginx
